### ISSUE TITLE
Cannot compile sample app/release using rebar 3.16.0

### ISSUE THREAD

**Issue by dendrown** [lfe/rebar3_lfe#68]
Hello,

I am getting an error compiling the lfe-app and lfe-release samples (as well as my own projects) when using version 3.16.0 of rebar3.
```bash
$ rebar3 version
rebar 3.16.0 on Erlang/OTP 23 Erts 11.1.7

$ rebar3 new lfe-release foobar
===> Writing foobar/README.md
===> Writing foobar/LICENSE
===> Writing foobar/rebar.config
===> Writing foobar/.gitignore
===> Writing foobar/apps/foobar/src/foobar.lfe
===> Writing foobar/apps/foobar/src/foobar-app.lfe
===> Writing foobar/apps/foobar/src/foobar-sup.lfe
===> Writing foobar/apps/foobar/src/foobar.app.src
===> Writing foobar/config/sys.config
===> Writing foobar/config/vm.args

 $ cd foobar
 $ rebar3 lfe compile
===> Fetching rebar3_lfe (from {git,"http://github.com/lfe-rebar3/rebar3_lfe",
                      {branch,"master"}})
===> Fetching lfe (from {git,"http://github.com/rvirding/lfe",{branch,"develop"}})
===> Analyzing applications...
===> Compiling lfe
===> Compiling rebar3_lfe
===> Verifying dependencies...
===> Fetching lfe (from {git,"http://github.com/rvirding/lfe",{branch,"develop"}})
===> Compiling foobar
===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"

$ rebar3 report lfe compile
Rebar3 report
 version 3.16.0
 generated at 2021-05-29T22:09:25+00:00
=================
Please submit this along with your issue at https://github.com/erlang/rebar3/issues (and feel free to edit out private information, if any)
-----------------
Task: lfecompile
Entered as:
  lfecompile
-----------------
Operating System: x86_64-pc-linux-gnu
ERTS: Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Root Directory: /usr/lib64/erlang
Library directory: /usr/lib64/erlang/lib
-----------------
Loaded Applications:
bbmustache: 1.10.0
certifi: 2.6.1
cf: 0.3.1
common_test: 1.19.1
compiler: 7.6.6
crypto: 4.8.3
cth_readable: 1.5.1
dialyzer: 4.3
edoc: 0.12
erlware_commons: 1.5.0
eunit: 2.6
eunit_formatters: 0.5.0
getopt: 1.0.1
hipe: 4.0.1
inets: 7.3.1
kernel: 7.2
providers: 1.8.1
public_key: 1.9.2
relx: 4.4.0
sasl: 4.0.1
snmp: 5.7.2
ssl_verify_fun: 1.1.6
stdlib: 3.14
syntax_tools: 2.4
tools: 3.4.2

-----------------
Escript path: undefined
Providers:
  app_discovery as clean clean clean-all clean-build clean-cache compile compile compile cover ct deps dialyzer do edoc escriptize escriptize eunit get-deps help install install_deps list lock new path pkgs release release relup repl report repos run run-escript run-release shell state tar tree unlock update upgrade upgrade upgrade version versions xref 
```
And looking at `rebar3.crashdump`:
```erlang
Error: undef
[{rebar_app_utils,app_src_to_app,
                  ["/dev/shm/foobar/_build/default/lib/foobar",
                   "/dev/shm/foobar/apps/foobar/src/foobar.app.src"],
                  []},
 {rebar3_lfe_utils,copy_app_src,1,
                   [{file,"/dev/shm/foobar/_build/default/plugins/rebar3_lfe/src/rebar3_lfe_utils.erl"},
                    {line,32}]},
 {rebar3_lfe_prv_compile,compile_app,1,
                         [{file,"/dev/shm/foobar/_build/default/plugins/rebar3_lfe/src/rebar3_lfe_prv_compile.erl"},
                          {line,59}]},
 {rebar3_lfe_prv_compile,'-compile/1-lc$^0/1-0-',1,
                         [{file,"/dev/shm/foobar/_build/default/plugins/rebar3_lfe/src/rebar3_lfe_prv_compile.erl"},
                          {line,54}]},
 {rebar3_lfe_prv_compile,compile,1,
                         [{file,"/dev/shm/foobar/_build/default/plugins/rebar3_lfe/src/rebar3_lfe_prv_compile.erl"},
                          {line,54}]},
 {rebar_core,do,2,
             [{file,"/home/ferd/code/self/rebar3/src/rebar_core.erl"},
              {line,155}]},
 {rebar_prv_do,do_task,5,
               [{file,"/home/ferd/code/self/rebar3/src/rebar_prv_do.erl"},
                {line,87}]},
 {rebar_core,do,2,
             [{file,"/home/ferd/code/self/rebar3/src/rebar_core.erl"},
              {line,155}]}]
```

This happens when using both the `release/0.3.x` and `release/0.2.x` branches of rebar3_lfe.  I had this problem running with LFE v2.0-dev over a couple versions of Erlang (22.3.2 and 23.2.3) I had installed on different servers.

What seems to have finally fixed the issue is downgrading rebar3 to version 3.14.1.

```bash
$ rebar3 version
===> Skipping lfe (from {git,"https://github.com/rvirding/lfe.git",{branch,"develop"}}) as an app of the same name has already been fetched
rebar 3.14.1 on Erlang/OTP 23 Erts 11.1.7
 
$ rebar3 lfe compile      
===> Skipping lfe (from {git,"https://github.com/rvirding/lfe.git",{branch,"develop"}}) as an app of the same name has already been fetched
===> Verifying dependencies...
===> Compiling foobar

# Success!
```

Even though there seems to be a work-around, I thought you may want to know.

Cheers,
den

**Comment by oubiwann** [comment]
Hey Den,

Yeah -- definitely aware of this (have run into it myself). I've got a plan to track a table of "working by default" sets of versions (LFE, Erlang, rebar3, etc.).

I use "working by default" because you can actually re-compile rebar3 locally for different versions of Erlang (which is the ultimate source of the problem we've all run into). Too lazy, though -- and I think that's true of many devs ;-) So probably good to have a table for people to reference ...

**Comment by dendrown** [comment]
Hi @oubiwann,

Yes, an easy look-up reference would be invaluable.  I imagine it's a challenge to keep the plugin  functioning correctly across the board with all the moving parts (active development on Erlang, LFE & rebar3).  As I believe you know, a fix for an issue I reported in LFE [#430](https://github.com/lfe/lfe/issues/430) may now have broken something when using the plugin with rebar 3.14.1, the version that fixed the problem I was having here.

Also, it helps just knowing up front that there may problems with different versions.  It took me a good while to figure out that the problem wasn't in my code.

Thanks,
den

**Comment by letrec** [comment]
Hello,

I'm getting the same error:

rebar3 --version
`rebar 3.17.0 on Erlang/OTP 24 Erts 12.2`

rebar3 report lfe compile
`Rebar3 report
 version 3.17.0
 generated at 2021-12-23T13:21:08+00:00
=================
Please submit this along with your issue at https://github.com/erlang/rebar3/issues (and feel free to edit out private information, if any)
-----------------
Task: lfecompile
Entered as:
  lfecompile
-----------------
Operating System: x86_64-pc-linux-gnu
ERTS: Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]
Root Directory: /home/user/kerl/24.2
Library directory: /home/user/kerl/24.2/lib
-----------------
Loaded Applications:
bbmustache: 1.10.0
certifi: 2.6.1
cf: 0.3.1
common_test: 1.22
compiler: 8.0.4
crypto: 5.0.5
cth_readable: 1.5.1
dialyzer: 4.4.3
edoc: 1.1
erlware_commons: 1.5.0
eunit: 2.7
eunit_formatters: 0.5.0
getopt: 1.0.1
inets: 7.5
kernel: 8.2
providers: 1.8.1
public_key: 1.11.3
relx: 4.5.0
sasl: 4.1.1
snmp: 5.11
ssl_verify_fun: 1.1.6
stdlib: 3.17
syntax_tools: 2.6
tools: 3.5.2

-----------------
Escript path: undefined
Providers:
  app_discovery as check clean clean clean-all clean-build clean-cache cmd compile compile compile confabulate cover coverage ct cut deps dialyzer do docs edoc escriptize escriptize eunit get-deps help install install_deps key list lock ltest new owner path pkgs publish release release relup repl repo report repos retire revert run run-escript run-release search shell state tar tree unlock update upgrade upgrade upgrade user version versions xref`

**Comment by letrec** [comment]
Switching to "2.0.1" version of lfe and "0.4.0" version of rebar3_lfe seems to resolve the issue.

**Comment by dendrown** [comment]
Confirmed: no issues when I upped rebar3_lfe to 0.4.0 with LFE 2.0.1 and rebar3 rebar 3.18.0.

@oubiwann, shall we close this ticket, or do you want to leave it open for your release tracking spreadsheet?

**Comment by dendrown** [comment]
Oops, I think I spoke too soon.  Although my larger project seems to be happy on the toolchain versions I listed above, I still get the problem for rebar3_lfe master, 0.4.0, 0.3.0, and 0.2.0.  I'm not sure what is allowing one to work, but not the other.

**Comment by oubiwann** [comment]
CI/CD with most recent LFE releases (2.0.1, 2.1.0) and rebar3_lfe releases (0.4.0, 0.4.1) show this has passing with the versions of rebar3 that ship with the Erlang v19-25 docker images.

I'm no longer running into this with the version of rebar3 that I have on my system, too (rebar 3.20.0 on Erlang/OTP 25 Erts 13.1.1).

Closing ...
