### ISSUE TITLE
`rebar3 new lfe-lib` creates rebar.config with outdated version of rebar_lfe plugin

### ISSUE THREAD

**Issue by MpdWalsh** [lfe/rebar3_lfe#72]
Hi there,

After a struggle trying to get up and running with rebar3 and LFE (and opening an [issue in the rebar3 repo](https://github.com/erlang/rebar3/issues/2593)), it seems like ya'll should know about what was going on. The title covers the issue. My workaround was to update the version number in the project's rebar.config myself and then run `rebar3 plugins upgrade rebar3_lfe`, but it would be nice if the project had already generated with the newest stable version.

**Comment by oubiwann** [comment]
Ugh, only seeing this now. Thanks for the submission -- working with Robert on some updates to things that will impact the plugin ...

**Comment by simon-mark-m** [comment]
Was about to log this, then I see you're already aware - it's listing 0.3.0 -- changing rebar.config to 0.4.0 seems to make it work, although I note there's still a few warnings/error, but I have absolutely no idea if they're significant. 
I get this (issues in bold)
===> Fetching rebar3_lfe v0.4.0
===> Fetching lfe v2.0.1
===> Fetching ltest v0.13.1
===> Fetching rebar_cmd v0.2.6
===> Fetching rebar3_hex v7.0.1
===> Fetching hex_core v0.8.4
===> Fetching verl v1.1.1
===> Analyzing applications...
===> Compiling verl
===> Compiling hex_core
===> Compiling rebar3_hex
_build/default/plugins/rebar3_hex/src/rebar3_hex_organization.erl:391:5: Warning: public_key:ssh_encode/2 is deprecated and will be removed in OTP 26; use ssh_file:encode/2 instead

===> Analyzing applications...
===> Compiling rebar_cmd
**===> "/home/smarkem/lfelib/_build/default/plugins/rebar_cmd/ebin/rebar_cmd.app" is missing applications entry**
===> Fetching erlang_color v1.0.0
===> Analyzing applications...
===> Compiling lfe
**_build/default/plugins/lfe/src/lfe_types.erl:76:21: Warning: variable '_L' is bound multiple times in this pattern. If you mean to ignore this value, use '_' or a different underscore-prefixed name
_build/default/plugins/lfe/src/lfe_types.erl:76:38: Warning: variable '_L' is bound multiple times in this pattern. If you mean to ignore this value, use '_' or a different underscore-prefixed name**

===> Compiling ltest
===> Compiling rebar3_lfe
===> Compiling color
===> Verifying dependencies...
===> Fetching lfe v2.0.0
===> Fetching ltest v0.13.0
===> Fetching erlang_color v1.0.0
===> Compiling lfelib
**===> Getting log of git repo failed in /home/smarkem/lfelib. Falling back to version 0.0.0**
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Apologies, but I'm just too new to LFE to know what to make of the above... 
The REPL at least works in a project now.

I'm guessing form the OP who logged this, that for an experienced user, diagnosing the version problem is pretty simple...
But, as this is referenced in introductory material, I'm guessing any noobs (like me) would have tripped at the first hurdle.

Here's the rebar report btw.. just in case it's helpful

**Rebar3 report**
 version 3.18.0
 generated at 2022-05-03T21:36:29+00:00
=================
Please submit this along with your issue at https://github.com/erlang/rebar3/issues (and feel free to edit out private information, if any)
-----------------
Task: rebar3
Entered as:
  rebar3 lfe repl
-----------------
Operating System: x86_64-pc-linux-gnu
ERTS: Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
Root Directory: /usr/lib/erlang
Library directory: /usr/lib/erlang/lib
-----------------
Loaded Applications:
bbmustache: 1.12.2
certifi: 2.8.0
cf: 0.3.1
common_test: 1.22.1
compiler: 8.1
crypto: 5.0.6
cth_readable: 1.5.1
dialyzer: 4.4.4
edoc: 1.1
erlware_commons: 1.5.0
eunit: 2.7
eunit_formatters: 0.5.0
getopt: 1.0.1
inets: 7.5.2
kernel: 8.3.1
providers: 1.9.0
public_key: 1.12
relx: 4.6.0
sasl: 4.1.2
snmp: 5.12
ssl_verify_fun: 1.1.6
stdlib: 3.17.1
syntax_tools: 2.6
tools: 3.5.2

-----------------
Escript path: undefined
Providers:
  app_discovery as build check clean clean clean-all clean-build clean-cache cmd compile compile compile confabulate cover coverage ct cut deps dialyzer do edoc escriptize escriptize eunit get-deps help install install_deps list lock ltest new organization owner path pkgs publish release release relup repl report repos retire run run-escript run-release search shell state tar tree unlock update upgrade upgrade upgrade user version versions xref

**Comment by simon-mark-m** [comment]
Just to add. I was taking a look at the 'Casting Spels in LFE' stuff.. and the project it suggests to download has a similar problem. i.e. it crashes when you try and start the REPL (it fails to build, I assume).
It's rebar.config contains:
  6 {deps, [
  5   {lfe, {git, "http://github.com/rvirding/lfe", {branch, "develop"}}}
  4 ]}.
  3
  2 {plugins, [
  1   {rebar3_lfe, {git, "http://github.com/lfe-rebar3/rebar3_lfe", {branch, "master"}}}
9   ]}.  

Which, with my limited understanding, implies its pulling in development / head branches?
Seems a bit chancy for what is essentially introductory material. 
Anyway, it doesn't work. (same general problems as the OP)

**Comment by wmealing** [comment]
Seeing the same thing,  I imagine this is a bit of a roadblock for new users.

**Comment by KingMob** [comment]
Any update on this? It's an absolute showstopper for newcomers, who won't know the commands to fix it.

**Comment by wmealing** [comment]
@KingMob Do you see where it in this repo that makes the broken configuration ?

This was the working configuration that I found.

 {deps, [
    {lfe, "2.0.1"},
    {ltest, "0.13.0"}
]}.

{plugins, [
    {rebar3_lfe, "0.4.0"}
]}.

**Comment by KingMob** [comment]
@wmealing Yeah, I was able to fix it. But I think I might just try out Elixir instead.

**Comment by oubiwann** [comment]
This has been fixed for a while ... (templates are now being updated from 0.4.0 to use LFE 2.1.0 and 0.4.1).
